# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, choices=[('c', 'CITE')], default='c', max_length=1)),
                ('BSCS', models.BooleanField(default=False)),
                ('BSIT', models.BooleanField(default=False)),
                ('BSIS', models.BooleanField(default=False)),
                ('BSCPE', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=200)),
                ('Sex', models.CharField(blank=True, choices=[('m', 'Male'), ('o', 'Female')], default='m', max_length=1)),
            ],
        ),
    ]
