# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department',
            field=models.CharField(blank=True, choices=[('cite', 'CITE')], default='cite', max_length=1),
        ),
    ]
