# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20180125_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Faculty_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='Department',
            field=models.CharField(blank=True, choices=[('cite', 'CITE')], default='cite', max_length=1),
        ),
    ]
