# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20180125_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department',
            field=models.CharField(blank=True, choices=[('C', 'CITE')], default='C', max_length=1),
        ),
    ]
