# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Question', '0002_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Name_of_Faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Faculty.detail'),
            preserve_default=False,
        ),
    ]
