# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_question_name_of_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
